### ISSUE TITLE
Recording doesn't follow vscode window

### ISSUE THREAD

**Issue by jednano** [arciisine/vscode-chronicler#11]
I guess I was assuming this extension would be confined to vscode and not other apps, including the desktop. Not sure if this is within the design goals or not, but if I move my vscode window to another monitor or resize it or whatever, the original vscode window location is what continues to be recorded.

**Comment by arciisine** [comment]
Yeah, this is the limitation with ffmpeg, as the recording area is defined as command line arguments.

**Comment by arciisine** [comment]
I'll update the docs to call this out, as it is not intuitive.

**Comment by jednano** [comment]
You might also want to point out the security / privacy implications of someone unintentionally revealing something they didn't intend to be visible underneath their vscode window.

**Comment by arciisine** [comment]
Not sure if I hit all the pieces, but it is called out that the recording is a rectangle on the screen, and not the window itself.

**Comment by jednano** [comment]
Thanks for adding clarity!
