### ISSUE TITLE
How to install this extension "vscode-chronicler" into Eclispe Theia?

### ISSUE THREAD

**Issue by cnruby** [arciisine/vscode-chronicler#20]
Hey!
## Help from Eclipse Theia
`To install something from the Marketplace into Eclipse Theia, you could use the prefix “vscode:extension/” followed by the ID of the VS Code extension. 
`

## Result
`root ERROR No plugin resolver found for the entry vscode:extension/arcsine.chronicler`

## Reference
- https://eclipsesource.com/blogs/2019/10/31/using-vs-code-extensions-in-eclipse-theia-and-che/

**Comment by arciisine** [comment]
I took a look, and initially I'm not sure how this is supposed to work out.  I'm pretty the IDE runs the plugins remotely which will be a problem for `ffmpeg` which is expected to capture the desktop buffer.  But it's also possible I didn't understand something fully either.

**Comment by cnruby** [comment]
Thanks for the reply!

Timothy Soehnlin <notifications@github.com> 于2020年4月14日周二 下午2:24写道：
