### ISSUE TITLE
4k displays support

### ISSUE THREAD

**Issue by lifeart** [arciisine/vscode-chronicler#22]
Currently, once I'm trying to record video on my PC, I'm getting only 1/4 of screen.

https://user-images.githubusercontent.com/1360552/104285404-a1cfb780-54c4-11eb-9dd7-35efff293d09.mp4

Extension works fine at 1920x1080, but record only part of screen for 3840x2160

**Comment by arciisine** [comment]
That's odd.  Nothing in the code should assume screen dimensions.  More
specifically we rely on OS apis to tell us the dimensions of the windows.

Do you have any pixel scaling on your display or is the output 1:1?  I know
this caused issues in the past for some OSs as well.

**Comment by lifeart** [comment]
@arciisine  in vscode console I have devicePixelRatio 2.5

![image](https://user-images.githubusercontent.com/1360552/104314150-123cff80-54ea-11eb-913b-4cb47672957e.png)

and for windows I have default scaling (250%)

![image](https://user-images.githubusercontent.com/1360552/104314253-3698dc00-54ea-11eb-8e1e-3c902ffbe1f2.png)

**Comment by arciisine** [comment]
I'm wondering if the pixel ratio has anything to do with it.  This will
come down to what dimensions I'm getting from Windows regarding the
dimensions.  https://www.npmjs.com/package/@arcsine/win-info, is what
determines the dimensions and then passes it on to ffmpeg.  I'll need to
figure out if it's tied to getting window details or if it's tied to an
ffmpeg limitation.

_tim

**Comment by arciisine** [comment]
This seems to point that I might need to have screen dpi awareness and do some multiplication on the coordinate system.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/948ec624-a506-45f7-a347-3c166ba34cea/getwindowrect-on-windows-10?forum=vcgeneral.

I might be able to provide a test build this weekend if you have the time to verify @lifeart.

**Comment by lifeart** [comment]
Sure, thank you!

**Comment by arciisine** [comment]
Still working on it. I've confirmed that ffmpeg is not DPI aware.  I'm working on this downstream.  First step will be https://github.com/arciisine/win-info/issues/1, and then https://github.com/arciisine/screen-recorder/issues/3.  After that I can update the plugin.

**Comment by arciisine** [comment]
@lifeart Okay, so modified the dependent libraries, and I've published a new version (0.1.9). Tested it on windows with multiple deskop scaling factors, and everything looked to be okay.

**Comment by lifeart** [comment]
@arciisine getting 
![image](https://user-images.githubusercontent.com/1360552/106389670-956cb980-63f5-11eb-8dba-e5ce0587c21a.png)

**Comment by arciisine** [comment]
@lifeart What version are you running? I remember running into this with some oddness in the JSON output of window information.  This was resolved in later builds.

**Comment by lifeart** [comment]
It’s 0.1.9 according to vscode

**Comment by arciisine** [comment]
So, I just pulled up 0.1.9 on my windows 10 VM and it appears to be working.  If I provide a simple repository, would you be able to run it and provide some debug information?  It would amount to running @arcsine/win-info commands to validate the bounds detection, as I believe this is where you are experiencing the problem.

**Comment by lifeart** [comment]
sure, no problem

**Comment by arciisine** [comment]
@lifeart , Try `npx -p @arcsine/win-info win-info` where you have `npx` installed.  

```
C:\Users\User>npx -p @arcsine/win-info win-info
npx: installed 1 in 2.441s
{
  "title": "npm",
  "id": 393890,
  "owner": {
    "name": "cmd.exe",
    "processId": 7528,
    "path": "C:\\Windows\\System32\\cmd.exe"
  },
  "screens": [
    {
      "x": 0,
      "y": 0,
      "width": 1707,
      "height": 1027,
      "index": 0,
      "scale": {
        "x": 2.25,
        "y": 2.25
      }
    }
  ],
  "bounds": {
    "x": 198,
    "y": 198,
    "width": 932,
    "height": 511
  }
}
```

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/106604247-6d559580-6570-11eb-8127-d45ed31b1de3.png)

**Comment by arciisine** [comment]
I'll need to modify the tool to display the full JSON on error.  I've never
seen "unexpected number in json" before, so pretty sure it's tied to that.
Thanks for working with me on this, I'll have another build out tonight if
you are able to run this again.

**Comment by arciisine** [comment]
@lifeart The latest verison (0.2.9) of the above script has been published, if you want to give it a try

**Comment by lifeart** [comment]
@arciisine  
![image](https://user-images.githubusercontent.com/1360552/106709499-b3106d80-6605-11eb-8645-79fcbbe7cc2b.png)

```json
{
    "title": "npm",
    "id": 920152,
    "owner": {
        "name": "WindowsTerminal.exe",
        "processId": 55928,
        "path": "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.5.10271.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe"
    },
    "screens": [
        {
          "x": 0,
          "y": 0,
          "width": 1536,
          "height": 824,
          "index": 0,
          "scale": {
            "x": 2,50,
            "y": 2,50
          }
        } ],
    "bounds": {
        "x": 388,
        "y": 166,
        "width": 1146,
        "height": 619
    }
}
```

**Comment by lifeart** [comment]
looks like `screens[0].scale.x` should be `2.50` instead of `2,50` and same for `y`

**Comment by arciisine** [comment]
@lifeart Thanks, this looks to be an issue of localization tied to the string formatting.  I'll get a release today or tomorrow.

**Comment by arciisine** [comment]
@lifeart Verified the fix, should be rolled out in the latest vscode chronicler update.  Thanks for all the assistance in finding (and troubleshooting).

**Comment by lifeart** [comment]
@arciisine thank you for your work! I can confirm, it's working as expected! (`v0.1.11`)
