### ISSUE TITLE
Invalid exit status: 1 when given a custom output directory

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [arciisine/vscode-chronicler#23]
Hello! I'm here to report that it gives an invalid exit status when i typed my custom output directory. All I typed was c:\Users\myself\Videos\VSCode Recordings. Unfortunately, that doesn't work! What can i do?

**Comment by arciisine** [comment]
I have a feeling the JSON config requires `\` to be `\\` for all slashes in your drive.

**Comment by arciisine** [comment]
Try `c:\\Users\\myself\\Videos\\VSCode Recordings` instead

**Comment by ENTPRESTIGIOUS** [comment]
I think I've already tried that but i'm gonna try it again later. I will let you know.

**Comment by arciisine** [comment]
And the space may also need a slash.  I'd actually recommend removing the space from the folder name, and using a dash or an underscore as a test.  Spaces tend to make things weird when using command line tools (which the extension does via ffmpeg).

**Comment by arciisine** [comment]
So, I should have a fix for this coming out today @ENTPRESTIGIOUS .  Not sure if you were able to work around the issue, but I'm now handling spaces in files more gracefully.

**Comment by ENTPRESTIGIOUS** [comment]
Sorry for not replying. Been busy back then. Apparently, I'm now getting an unavoidable Invalid exit status: 1 which means that even if i reset the setting to default, it also gives me an error!
