### ISSUE TITLE
Invalid Exit Status: 1 now happening even with default directory!

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [arciisine/vscode-chronicler#27]
Sorry for not replying. Been busy back then. Apparently, I'm now getting an unavoidable Invalid exit status: 1 which means that even if i reset the setting to default, it also gives me an error!

_Originally posted by @ENTPRESTIGIOUS in https://github.com/arciisine/vscode-chronicler/issues/23#issuecomment-879508923_

**Comment by ENTPRESTIGIOUS** [comment]
I have tried reinstalling too without changing anything but no luck!

**Comment by arciisine** [comment]
Hmm, sorry if this was mentioned in another thread, but what platform are you running on?   Also if you can, please run `npx @arcsine/screen-recorder test.mp4` and `npx @arcsine/win-info` from the command line, then the output should help identify the problem.

**Comment by CHENCHETY-ABHISHEK** [comment]
# chronicler invalid exit status 1

[Invalid Exit Status: 1 now happening even with default directory! · Issue #27 · arciisine/vscode-chronicler](https://github.com/arciisine/vscode-chronicler/issues/27)

- it occurs if there is no ffmpeg.exe file in the required path.
- to solve this go to settings.json from command palate and comment the chronicler line as shown in below figure.

![Untitled](https://user-images.githubusercontent.com/88726684/146682234-48bcd910-a397-4566-9ea3-e096d60ae76b.png)


- now try to start recording and you will see popup at bottom right as shown below

![Untitled 1](https://user-images.githubusercontent.com/88726684/146682237-fa309bf1-1298-4536-9d9d-625271df35a4.png)




- Now download it.. and start recording using command palate

NOTE: some systems give an invalid file while viewing the recording.

Make sure that you have proper tools to view the recording.
