### ISSUE TITLE
Error parsing data

### ISSUE THREAD

**Issue by evsar3** [arciisine/vscode-chronicler#28]
```json
{
    "title": "? Untitled-1 - main - Visual Studio Code",
    "id": 1575502,
    "owner": {
        "name": "Code.exe",
        "processId": 29468,
        "path": "C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe"
    },
    "screens": [
        {
            "x": 0,
            "y": 0,
            "width": 3840,
            "height": 2120,
            "index": 0,
            "scale": {
                "x": 1,00,
                "y": 1,00
            }
        }
    ],
    "bounds": {
        "x": 2,
        "y": 2,
        "width": 1916,
        "height": 2116
    }
}
```
As seem on the JSON above, the scale is getting wrong decimal separator.

It seems the fix in https://github.com/arciisine/vscode-chronicler/commit/530c7d1db181cc337ce5c6a581af515180dc2643 didn't apply to me.
Running `VS Code v1.58.2` and `Chronicler v0.1.12`

![Extension Chronicler - main - Visual Studio Code](https://user-images.githubusercontent.com/1992754/126404603-d4423dd4-59b0-4dff-b9c6-cc58b7529a39.jpg)

My locale is `pt-BR`

**Comment by arciisine** [comment]
I had this issue before when dealing with Number formatting within C# (on Win platforms).  That should have all been resolved, but there is obviously an issue here.  Let me take a look and see if I can't get a fix out shortly.

**Comment by arciisine** [comment]
I should have a fix released, @ 0.1.14.  Apparently I had a reverted a previous fix for localization issues.  Should be working now.

**Comment by evsar3** [comment]
v0.1.14 fixed the issue... I was investigating and was about to publish a pull request of the `CultureInfo.InvariantCulture` patch on win-info then I got this issue notification.

Thank you for your amazing extension!

**Comment by arciisine** [comment]
Thanks so much for the feedback, and PRs are always welcomed :-).  Glad you are enjoying it.
