### ISSUE TITLE
Error: "Cannot read property 'uri' of undefined" when no folder in workspace

### ISSUE THREAD

**Issue by ogmios-voice** [arciisine/vscode-chronicler#30]
When trying to start recording in a workspace w/ no folder Chronicler throws the _"Cannot read property 'uri' of undefined"_ error.

See also: https://code.visualstudio.com/docs/editor/workspaces#_can-i-use-a-multiroot-workspace-without-folders

> Can I use a multi-root workspace without folders?
> It is possible to leave the `folders` section of a `.code-workspace` file empty so that you end up with an instance of VS Code that does not show any root folders. You can still store workspace settings and even tasks or launch configurations in this case.

**Comment by arciisine** [comment]
Thanks for the report.  Yeah, this should be doable, just not a normal pattern for my own development.  Let me take a look and see what the level of effort is to remove the workspace assumption.

**Comment by arciisine** [comment]
Most of the work was already done for this.  I made a few minor changes, and this should be working now.
