### ISSUE TITLE
Can't get the plugin to record. Maybe issue with being in a remote container?

### ISSUE THREAD

**Issue by george-codes** [arciisine/vscode-chronicler#33]
I have a development container I run with using .devcontainer deployment in VSCode. It's running Ubuntu 20.04 (if that helps). When I attempt to record, I get the countdown... then right at "0", I get the following error. I will take a look at your repo, see if I can figure out anything. Let me know if you want me to try anything. thanks.

Command failed: /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /root/.vscode-server/extensions/arcsine.chronicler-0.1.16/node_modules/@arcsine/win-info/bin/win-info-x11.js active node:internal/errors:464 ErrorCaptureStackTrace(err); ^ Error: spawn xprop ENOENT at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19) at onErrorNT (node:internal/child_process:477:16) at processTicksAndRejections (node:internal/process/task_queues:83:21) { errno: -2, code: 'ENOENT', syscall: 'spawn xprop', path: 'xprop', spawnargs: [ '-root', '\t$0', '_NET_ACTIVE_WINDOW' ], cmd: 'xprop -root \t$0 _NET_ACTIVE_WINDOW', stdout: '', stderr: '' }

**Comment by arciisine** [comment]
Yeah, so this isn't going to work in a remote container, as the ffmpeg binary needs to run with knowledge/access of the windows/applications.  The only way this would work is if the extension runs locally, but I'm not sure what that would look like.

**Comment by george-codes** [comment]
Okay, understood. thanks for the reply.
