### ISSUE TITLE
Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by andrepadez** [arciisine/vscode-chronicler#35]
Using Mac OS Monterey vs 12.6, VSCode 1.71.2

Getting this error after the countdown "Starting in x seconds".

I already gave "Screen Recording" permissions to VS Code.

<img width="476" alt="Screenshot 2022-09-26 at 22 33 46" src="https://user-images.githubusercontent.com/1013997/192384788-6c603741-b829-417e-a9ed-48a6d757f6df.png">

Much appreciated

**Comment by arciisine** [comment]
@andrepadez   If you can, please run `npx @arcsine/screen-recorder test.mp4` from the command line, and the output should help identify the problem.  Its possible ffmpeg (the underlying recording tool) is what needs permissions, and not vscode.

**Comment by andrepadez** [comment]
Wow, thanks for the quick reply...
Let me add that i installed ffmpeg when prompted the first time running your extension.
Here's the output:

<img width="1136" alt="Screenshot 2022-09-26 at 23 42 43" src="https://user-images.githubusercontent.com/1013997/192393483-da82996d-2471-494a-9b27-9783fcd75dcf.png">

**Comment by arciisine** [comment]
Oh wow, that doesn't seem right at all.  I'm running from linux, but you should see something closer to:

```
$ npx @arcsine/screen-recorder test.mp4
/usr/bin/ffmpeg -threads 4 -video_size 1920x1200 -f x11grab -i :0+0,0 -preset ultrafast -crf 10 -pix_fmt yuvj444p -c:v libx264 -y  test.mp4
Recording for 5 seconds...
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  ```
  
  The error about yauzl seems really wrong.  Perhaps try again?  And maybe install ffmpeg globally as a test as well (if you are using brew, it should be easily installable).

**Comment by andrepadez** [comment]
installing ffmpeg now, will get back asap

**Comment by andrepadez** [comment]
Sorry for the late reply, tried several things...
Ended up cleaning npm cache and was able to run it better, but still with problems at the end, when `Ctrl+c`


<img width="1056" alt="Screenshot 2022-09-27 at 00 49 40" src="https://user-images.githubusercontent.com/1013997/192400261-10b8f434-bc11-442b-ae99-73fa74f83fff.png">

**Comment by arciisine** [comment]
Okay, so that means ffmpeg is not happy with your device, can run
`/opt/homebrew/bin/ffmpeg -f avfoundation -list_devices true -i ""`?  This
is what the underlying program launches to determine what screen recording
devices are available.

**Comment by andrepadez** [comment]
<img width="1033" alt="Screenshot 2022-09-27 at 01 54 22" src="https://user-images.githubusercontent.com/1013997/192406625-f1433700-9bc3-4d9a-b110-9505be9d142d.png">

**Comment by arciisine** [comment]
The input/output error response seems a little odd, but that is looking
mostly correct.  Can you try updating your workspace settings to use
/opt/homebrew/bin/ffmpeg for the ffmpeg path, versus the version that was
installed earlier?

[image: image.png]

**Comment by andrepadez** [comment]
It worked! Thanks a lot.
Just an aside question, is there a way to record code and browser at the same time?
You don't have to answer it, you can just close the issue as resolved, i'm very appreciative of your support.

Cheers

**Comment by andrepadez** [comment]
Found it, thanks a million!

**Comment by arciisine** [comment]
> It worked! Thanks a lot. Just an aside question, is there a way to record code and browser at the same time? You don't have to answer it, you can just close the issue as resolved, i'm very appreciative of your support.
> 
> Cheers

ffmpeg is the one doing all the work here, so realistically, you can use it to record multiple screens, and do quite a bit more.  Though as it gets more complicated, a tool like OBS may be better suited for your needs.  

If there is a clear idea/feature that you are thinking of, do feel free to open an issue, as it would be worth discussing.
