### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by ed-sparkes** [arciisine/vscode-chronicler#6]
Says starting recording in 5..4..3..2..1 but then doesn't start recording, does nothing. 

Are there any logs anywhere i could look at to see what is going wrong. 

I have installed 4.1.1 of FFMPEG from here https://ffmpeg.zeranoe.com/builds/

Many thanks, Ed

**Comment by arciisine** [comment]
@ed-sparkes Thanks for the report.  Last I checked windows was working fine.  There should be log output under the chronicler plugin output.  Additionally, have you tried letting the plugin install ffmpeg for you?  Could be a path issue.  

I will give windows another check later tonight to see if anything is up.

**Comment by ed-sparkes** [comment]
Hmm interesting, i tried letting the plugin install ffmpeg and now it works but not in all my workspaces. 

I have a java project. And in there it counts down but doesnt run or do anything, just goes straight back to the start button. But in another workspace for a .net and javascript project it works, strange

**Comment by arciisine** [comment]
Is it possible to share the workspace, or atleast the vscode settings for the workspace?  Nothing is specific to any language, just the vscode version

**Comment by ed-sparkes** [comment]
These are my only settings and they are user settings not workspace
settings so same across all workspaces.

Yes the java repository i have still doesnt start the recorder whilst all
my others ones do  bizarre, annoyingly its the java one i wanted to record

{
"java.home": "C:\\Program Files\\Java\\jdk1.8.0_151",
"java.configuration.checkProjectSettingsExclusions": false,

"terminal.integrated.shell.windows": "cmd.exe",
"terminal.integrated.fontFamily":"Fira Code",
"terminal.integrated.env.windows": {
"CMDER_ROOT": "C:\\Utils\\cmder"
},
"terminal.integrated.shellArgs.windows": [
"/k C:\\Utils\\cmder\\vendor\\init.bat"
],
"editor.suggestSelection": "first",
"vsintellicode.modify.editor.suggestSelection":
"automaticallyOverrodeDefaultValue",
"chronicler.dest-folder": "~/Recordings",
"chronicler.debug": true,
"chronicler.ffmpeg-binary": "c:\\Users\\MYUSERNAME\\FF/ffmpeg.exe",
"window.zoomLevel": 0,
}

**Comment by ed-sparkes** [comment]
Even weirder, if i go up a folder to the parent folder it works fine but in
the one folder i actually want to record its not working, are there any
hidden vscode settings that could be interfering?

**Comment by arciisine** [comment]
Are you sure there isn't a .vscode folder/settings in the folder that isn't working?  This seems really odd.

**Comment by arciisine** [comment]
@ed-sparkes Were you able to figure it out?

**Comment by ed-sparkes** [comment]
Nope, most frustrating, could it be not playing nice with some other
extension that is active in the workspace? Cant find any logs anywhere the
recording just doesnt start :(

**Comment by arciisine** [comment]
I'm verifying the debug messages, and I can't seem to pull them up other.  Let me take a look, I might need to push out an update to resolve this.

**Comment by arciisine** [comment]
So I didn't even realize, that when I broke out the screen-recording functionality to an external library, that I lost all of my logging.  I will take some time to get that back to where it needs to be.  If you have a  reference project and could let me know the version of windows you are running, that would be helpful.  I'd like to try to reproduce your issue locally.

**Comment by ed-sparkes** [comment]
Hi, so bizarre on the command line  i ran cp -r myproject examplefortesting
plan was to pair back my code to something generic that still failed that i
could share with you. But i thought ill just test record first and it
worked, yet in the original folder myproject it still doesnt work.

Ed

**Comment by ed-sparkes** [comment]
Any tips on how to optimise gifs produced? The size seems to depend on the
resolution of the monitor on which the recording takes place, which kinda
makes sense but not sure i need 4k quality at 5mb for 10 second gif, and
nor does my gitrepos readme.md :)

Thanks, Ed

**Comment by arciisine** [comment]
@ed-sparkes Sorry for the delay, missed this in the back and forth.  You should be able to affect the ffmpeg settings and set the resolution of the output, let me take a look and I should be able to post something this weekend.

**Comment by arciisine** [comment]
@ed-sparkes The tool now supports setting a property to scale the output animated GIF.
