### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by jednano** [arciisine/vscode-chronicler#9]
When I start recording with Audio, specifically, I get a countdown, but when it hits zero I get this error:

<img width="564" alt="Screen Shot 2019-10-03 at 1 57 29 PM" src="https://user-images.githubusercontent.com/1058243/66155695-d5474500-e5e5-11e9-86a7-2e146ebf9f0a.png">

Environment: macOS Mojave v10.14.6
ffmpeg installed via `brew install ffmpeg`

**Comment by arciisine** [comment]
Thanks. Let me take a look and see where the problem is.  Also make sure tm
your ffmpeg install has audio support.

**Comment by jednano** [comment]
The [custom build of FFmpeg](https://github.com/arciisine/vscode-chronicler/binaries/osx/ffmpeg) link is a 404 in the readme and I had a hard time following the [more info](https://trac.ffmpeg.org/ticket/4513) link on how to do a custom build for macOS.

**Comment by arciisine** [comment]
Yeah, its just the wrong path in the readme, https://github.com/arciisine/vscode-chronicler/tree/master/binaries/osx is where that is at.  Give that a try.  And I'm assuming you are on a mac/

**Comment by jednano** [comment]
I am on a mac. I provided my env in the initial comment.

As for that `ffmpeg` file, I replaced my `brew cask install ffmpeg` version with that one and gave it permissions with `chmod 755` and ran it, but I get the error:

```
dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.165.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
Abort trap: 6
```

If I do `brew install x265` it's already installed:

```
Warning: x265 3.1.2 is already installed and up-to-date
To reinstall 3.1.2, run `brew reinstall x265`
```

Starting to think this might be more trouble than it's worth 😢

**Comment by arciisine** [comment]
I don't have a mac as my daily driver anymore, but I can pull it up on one.  Will probably take a me a few days, but I'll see if there is anything special on my side.  FFmpeg was really finicky, and getting fixes upstreamed proved to not really be an option (hence the custom ffmpeg).  

It might be as simple as uploading a new custom binary that is built against the latest libx265

**Comment by arciisine** [comment]
And the issue you had about `toString` of undefined, sounds like it could be something else as well.  I'll just need to fire up a mac.

**Comment by arciisine** [comment]
Just published an update to the plugin, this should be resolved.  I also updated the binary, and should provide better audio.

**Comment by jednano** [comment]
Excellent! Is the binary in the same location?

**Comment by arciisine** [comment]
Yeah,
https://github.com/arciisine/vscode-chronicler/tree/master/binaries/osx.  I
might need to recompile that, but my laptop was behaving a little odd.

**Comment by jednano** [comment]
Just so you know, it works! Thanks!
